### PR TITLE
Add stale notice

### PR DESCRIPTION
**Pull request by MariusRumpf**
Adds a stale notice and a reference to the fork.

### CODE REVIEW

**Comment by ristomatti** [comment]
LGTM. Thanks! I would've done this ages ago but either forgot or didn't notice I could've likely done it.

Do you own any LIFX devices anymore BTW?

**Comment by ristomatti** [comment]
Maybe you should archive the repo as well to make it clear?

**Comment by MariusRumpf** [comment]
I still own and use the LIFX Original and a Mini White, but I never overcame the issue in an rental apartment that the light switches turns the power of the light off.
I think deprecating the npm package would be even better for communication.
I don't remember clearly but I think I gave you the collaboration rights when I saw that you forked it, but had no time for more communication at that moment.

**Comment by ristomatti** [comment]
I've using white electrical tape to prevent the hard switches from being toggled :slightly_smiling_face:. And yes I think you're right. Why i got things mixed up was the fact I wasn't able to push a new version of the npm package, so merging further PR's would have been pointless. But this has now been sorted out with the fork.

Thanks for the time spent on this library :bow:. It tells a lot about the original design that most of the functionality is still the same. Great work! It's still a core part of my home automation via a Node-RED plugin [ristomatti/node-red-contrib-node-lifx](https://github.com/ristomatti/node-red-contrib-node-lifx).

I control the lights using Mi-Ligth remotes. The Mi-Light specific 2.4GHz signals are captured by an ESP8266 running [sidoh/esp8266_milight_hub](https://github.com/sidoh/esp8266_milight_hub), sent to Node-RED via MQTT. In Node-RED the Mi-Ligth RGBW data is converted to format recognized by node-lifx and the group/light id's of the controller get mapped to LIFX light labels configured in YAML.  Data is then routed to matching node-red-contrib-node-lifx specific light nodes which then handles the node-lifx interaction. This hacky setup has worked near perfectly around 4-5 years now. The lights react to controls without any noticeable delay (unline with Zigbee for instance) :sunglasses:.

**Pull request merged**
